In [1]:
import numpy as np 

## Creating arrays
Arrays can be created in a number of ways and using different methods.

In [3]:
# Create a simple 1 dimensional array
one_dim = [1, 2, 3, 4]
print(f'One Dimensional Array: {np.array(one_dim)}')

# Create a 2 dimensional array
two_dim = np.array([[3, 4], [5, 6]])
print(f'Two Dimensional Array:\n{two_dim}')

One Dimensional Array: [1 2 3 4]
Two Dimensional Array:
[[3 4]
 [5 6]]


The methods zeros() and ones() fills the array with zeros and ones respectively. The default data type is a float; however it can be change to an integer by using the *dtype=* attribute.

In [5]:
zero_int = np.zeros((2, 3), dtype=int)
zero_int

array([[0, 0, 0],
       [0, 0, 0]])

The method full() uses a *fill_value* attribute to fill the array with the given value.

In [6]:
fill_with_sixes = np.full((2, 3), fill_value=6)
fill_with_sixes

array([[6, 6, 6],
       [6, 6, 6]])

The eye method creates the identity matrix, that is, a matrix with elements on the diagonal are set to one, and non-diagonal elements are set to zero.

In [7]:
identity_matrix = np.eye(7, dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

The arange() method creates an array based on the soecified values for integers, while linspace does the same for none integer values.

In [9]:
create_range = np.arange(0, 12, 2)  # starts at 0 and skips 2
print(f'Using Arange:\n{create_range}\n')

non_ints = np.linspace(0, np.pi, 4) # evenly spaced with 4 elements
print(f'Using Linspace:\n{non_ints}')

Using Arange:
[ 0  2  4  6  8 10]

Using Linspace:
[0.         1.04719755 2.0943951  3.14159265]
